#ifndef LIBSURAIMUENGINE_DEFAULTS_H_INCLUDED
#define LIBSURAIMUENGINE_DEFAULTS_H_INCLUDED

const int GAMEWINDOW_WIDTH = 640;
const int GAMEWINDOW_HEIGHT = 480;

#endif // LIBSURAIMUENGINE_DEFAULTS_H_INCLUDED